apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: app-dev
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 1Gi

---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: app-dev
spec:
  limits:
  - default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container